[context.production]
  command = "npm start"
  environment = { ACCESS_TOKEN = "super secret", NODE_VERSION = "8.0.1" }

[dev]
  command = "npm start"
  framework = "#custom"
  port=8000 # destination port to use in browser. Lambda dev server is started on same port
  targetPort=3000 # port that local rollup server is running on